services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: product_catalog
      DB_USERNAME: october
      DB_PASSWORD: happyoctober
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: product_catalog
      POSTGRES_USER: october
      POSTGRES_PASSWORD: happyoctober
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  pgdata: